### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by AnkushVerma000** [varunKT001/tomper-wear-ecommerce-admin#1]
Add dark theme and  make a responsive sheet that can help you for user reviews and also add that type of system which help peoples to sell their products who does not know more about Internet basically belongs to rural area

**Comment by varunKT001** [comment]
Hey @AnkushVerma000 👋

- I'll be creating an issue form soon (since many of you guys never follow the template properly 😕), then you can create a new issue. 
- Since, this repository is not as active as the main TomperWear repository, I've not yet configured some important workflows. I'll do that soon.
- Also, try to add some more details while making an issue.

For now, I'm closing this issue, you can create a new one once things are configured 👍
